#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 12, 2017 12:46:22 AM
import sys
import QuestionType
import Database
import Login



try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import Instructor_support
import Database
import profile


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = CreateAQuiz (root)
    Instructor_support.init(root, top)
    root.mainloop()

w = None
def create_CreateAQuiz(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = CreateAQuiz (w)
    Instructor_support.init(w, top, *args, **kwargs)
    return (w, top)



class CreateAQuiz:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Black} -size 11 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font12 = "-family {Segoe UI Black} -size 24 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("729x552+359+93")
        top.title("CreateAQuiz")
        top.configure(background="#333333")



        self.CreationFrame = Frame(top)
        self.CreationFrame.place(relx=0.26, rely=0.25, relheight=0.5
                , relwidth=0.53)
        self.CreationFrame.configure(relief=GROOVE)
        self.CreationFrame.configure(borderwidth="1")
        self.CreationFrame.configure(relief=GROOVE)
        self.CreationFrame.configure(background="#00ffff")
        self.CreationFrame.configure(width=385)

        self.DescriptionLabel = Label(self.CreationFrame)
        self.DescriptionLabel.place(relx=0.18, rely=0.33, height=21, width=254)
        self.DescriptionLabel.configure(activebackground="#f9f9f9")
        self.DescriptionLabel.configure(activeforeground="black")
        self.DescriptionLabel.configure(background="#333333")
        self.DescriptionLabel.configure(disabledforeground="#a3a3a3")
        self.DescriptionLabel.configure(font=font10)
        self.DescriptionLabel.configure(foreground="#ffffff")
        self.DescriptionLabel.configure(highlightbackground="#d9d9d9")
        self.DescriptionLabel.configure(highlightcolor="black")
        self.DescriptionLabel.configure(text='''Description''')
        self.DescriptionLabel.configure(width=254)

        self.DescriptionEntry = Entry(self.CreationFrame)
        self.DescriptionEntry.place(relx=0.18, rely=0.44, relheight=0.36
                , relwidth=0.66)
        self.DescriptionEntry.configure(background="white")
        self.DescriptionEntry.configure(disabledforeground="#a3a3a3")
        self.DescriptionEntry.configure(font="TkFixedFont")
        self.DescriptionEntry.configure(foreground="#000000")
        self.DescriptionEntry.configure(highlightbackground="#d9d9d9")
        self.DescriptionEntry.configure(highlightcolor="black")
        self.DescriptionEntry.configure(insertbackground="black")
        self.DescriptionEntry.configure(selectbackground="#c4c4c4")
        self.DescriptionEntry.configure(selectforeground="black")
        self.DescriptionEntry.configure(width=254)

        self.TitleLabel = Label(self.CreationFrame)
        self.TitleLabel.place(relx=0.18, rely=0.11, height=21, width=254)
        self.TitleLabel.configure(activebackground="#f9f9f9")
        self.TitleLabel.configure(activeforeground="black")
        self.TitleLabel.configure(background="#333333")
        self.TitleLabel.configure(disabledforeground="#a3a3a3")
        self.TitleLabel.configure(font=font10)
        self.TitleLabel.configure(foreground="#ffffff")
        self.TitleLabel.configure(highlightbackground="#d9d9d9")
        self.TitleLabel.configure(highlightcolor="black")
        self.TitleLabel.configure(text='''Title''')
        self.TitleLabel.configure(width=254)

        self.TitleEntry = Entry(self.CreationFrame)
        self.TitleEntry.place(relx=0.18, rely=0.22, relheight=0.07
                , relwidth=0.66)
        self.TitleEntry.configure(background="white")
        self.TitleEntry.configure(disabledforeground="#a3a3a3")
        self.TitleEntry.configure(font="TkFixedFont")
        self.TitleEntry.configure(foreground="#000000")
        self.TitleEntry.configure(highlightbackground="#d9d9d9")
        self.TitleEntry.configure(highlightcolor="black")
        self.TitleEntry.configure(insertbackground="black")
        self.TitleEntry.configure(selectbackground="#c4c4c4")
        self.TitleEntry.configure(selectforeground="black")
        self.TitleEntry.configure(width=254)

        self.Logo = Label(top)
        self.Logo.place(relx=0.36, rely=0.14, height=41, width=211)
        self.Logo.configure(background="#333333")
        self.Logo.configure(disabledforeground="#a3a3a3")
        self.Logo.configure(font=font12)
        self.Logo.configure(foreground="#ffffff")
        self.Logo.configure(text='''Create a quiz''')
        self.Logo.configure(width=211)



        def getTitle(t,d):
            I=Login.instructor.getUserName()
            print t

            #sql = "INSERT INTO quiz(title) values%(s)"
            #temp=Database.cursor.execute(sql,(t))
            #Database.c.execute("INSERT INTO Quiz (Title,Description,Instructor) VALUES(?,?,?)", (t, d, I))
            Database.c.execute("INSERT INTO Question (qTitle,qDescription,InstructorName) VALUES(?,?,?)",(t,d,I))
            Database.conn.commit()

            #cursor = Database.c.execute("SELECT (qTitle,qDescription,InstructorName) from Question")
            #for row in cursor:
             #   print "ID",row[0]
              #  print "Title",row[1]
               # print "des",row[2]            #Database.conn.close()
            root.destroy()
            QuestionType.vp_start_gui()



        self.LogInButton = Button(self.CreationFrame, command= lambda : getTitle(self.TitleEntry.get(),self.DescriptionEntry.get() ))
        self.LogInButton.place(relx=0.36, rely=0.84, height=24, width=107)
        self.LogInButton.configure(activebackground="#d9d9d9")
        self.LogInButton.configure(activeforeground="#000000")
        self.LogInButton.configure(background="#333333")
        self.LogInButton.configure(disabledforeground="#a3a3a3")
        self.LogInButton.configure(font=font10)
        self.LogInButton.configure(foreground="#ffffff")
        self.LogInButton.configure(highlightbackground="#d9d9d9")
        self.LogInButton.configure(highlightcolor="black")
        self.LogInButton.configure(pady="0")
        self.LogInButton.configure(text='''Submit''')
        self.LogInButton.configure(width=107)





if __name__ == '__main__':
    vp_start_gui()
    profile.run('vp_start_gui()')



