#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 12, 2017 12:35:44 AM
import sys
import user
import Instructor
import StudentView
import tkMessageBox as M



try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import Login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Login (root)
    Login_support.init(root, top)
    root.mainloop()

w = None
def create_Login(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Login (w)
    Login_support.init(w, top, *args, **kwargs)
    return (w, top)



instructor = user.User("Umar", "abc","teacher")

Student = user.User("Danyal","xyz","student")
class Login:
    role = ""

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Black} -size 11 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font11 = "-family {@Microsoft JhengHei} -size 10 -weight "  \
            "normal -slant roman -underline 0 -overstrike 0"
        font12 = "-family {Segoe UI Black} -size 24 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("729x552+359+93")
        top.title("Login")
        top.configure(background="#333333")



        self.LoginFrame = Frame(top)
        self.LoginFrame.place(relx=0.52, rely=0.24, relheight=0.43
                , relwidth=0.45)
        self.LoginFrame.configure(relief=GROOVE)
        self.LoginFrame.configure(borderwidth="1")
        self.LoginFrame.configure(relief=GROOVE)
        self.LoginFrame.configure(background="#00ffff")
        self.LoginFrame.configure(width=325)

        self.UserNameLabel = Label(self.LoginFrame)
        self.UserNameLabel.place(relx=0.22, rely=0.21, height=21, width=194)
        self.UserNameLabel.configure(background="#333333")
        self.UserNameLabel.configure(disabledforeground="#a3a3a3")
        self.UserNameLabel.configure(font=font10)
        self.UserNameLabel.configure(foreground="#ffffff")
        self.UserNameLabel.configure(text='''User Name''')
        self.UserNameLabel.configure(width=194)

        self.PasswordLabel = Label(self.LoginFrame)
        self.PasswordLabel.place(relx=0.22, rely=0.47, height=21, width=194)
        self.PasswordLabel.configure(activebackground="#f9f9f9")
        self.PasswordLabel.configure(activeforeground="black")
        self.PasswordLabel.configure(background="#333333")
        self.PasswordLabel.configure(disabledforeground="#a3a3a3")
        self.PasswordLabel.configure(font=font10)
        self.PasswordLabel.configure(foreground="#ffffff")
        self.PasswordLabel.configure(highlightbackground="#d9d9d9")
        self.PasswordLabel.configure(highlightcolor="black")
        self.PasswordLabel.configure(text='''Password''')

        self.UserNameEntry = Entry(self.LoginFrame)
        self.UserNameEntry.place(relx=0.22, rely=0.34, relheight=0.09
                , relwidth=0.6)
        self.UserNameEntry.configure(background="white")
        self.UserNameEntry.configure(disabledforeground="#a3a3a3")
        self.UserNameEntry.configure(font=font11)
        self.UserNameEntry.configure(foreground="#000000")
        self.UserNameEntry.configure(insertbackground="black")
        self.UserNameEntry.configure(width=194)

        self.PasswordEntry = Entry(self.LoginFrame)
        self.PasswordEntry.place(relx=0.22, rely=0.6, relheight=0.09
                , relwidth=0.6)
        self.PasswordEntry.configure(background="white",show= "*")
        self.PasswordEntry.configure(disabledforeground="#a3a3a3")
        self.PasswordEntry.configure(font="TkFixedFont")
        self.PasswordEntry.configure(foreground="#000000")
        self.PasswordEntry.configure(highlightbackground="#d9d9d9")
        self.PasswordEntry.configure(highlightcolor="black")
        self.PasswordEntry.configure(insertbackground="black")
        self.PasswordEntry.configure(selectbackground="#c4c4c4")
        self.PasswordEntry.configure(selectforeground="black")



        self.LogInButton = Button(self.LoginFrame, command= lambda : getUserNamePassword(self.UserNameEntry.get(),self.PasswordEntry.get() ))
        self.LogInButton.place(relx=0.37, rely=0.72, height=24, width=97)
        self.LogInButton.configure(activebackground="#d9d9d9")
        self.LogInButton.configure(activeforeground="#000000")
        self.LogInButton.configure(background="#333333")
        self.LogInButton.configure(disabledforeground="#a3a3a3")
        self.LogInButton.configure(font=font10)
        self.LogInButton.configure(foreground="#ffffff")
        self.LogInButton.configure(highlightbackground="#d9d9d9")
        self.LogInButton.configure(highlightcolor="black")
        self.LogInButton.configure(pady="0")
        self.LogInButton.configure(text='''Log In''')
        self.LogInButton.configure(width=97)

        self.Logo = Label(top)
        self.Logo.place(relx=0.11, rely=0.4, height=41, width=191)
        self.Logo.configure(background="#333333")
        self.Logo.configure(disabledforeground="#a3a3a3")
        self.Logo.configure(font=font12)
        self.Logo.configure(foreground="#ffffff")
        self.Logo.configure(text='''Digital Quiz''')
        self.Logo.configure(width=191)


        def getUserNamePassword(u,p):
            if u == instructor.getUserName() and p == instructor.getPassword():
                self.role = instructor.getRole()
                root.destroy()
                Instructor.vp_start_gui()


            elif u == Student.getUserName() and p == Student.getPassword():
                self.role = Student.getRole()
                root.destroy()
                StudentView.vp_start_gui()
                print self.role
            else: M.showerror("Error","Wrong Credentials")


if __name__ == '__main__':
    vp_start_gui()





