#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI Black} -size 11 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Segoe UI Black} -size 18 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font14
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top60
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra61
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top60 {base} {
    if {$base == ""} {
        set base .top60
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#333333} 
    wm focusmodel $top passive
    wm geometry $top 688x525+371+102
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1362 741
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "MCQ"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra61 \
        -borderwidth 2 -relief groove -background {#00ffff} -height 345 \
        -width 595 
    vTcl:DefineAlias "$top.fra61" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra61
    entry $site_3_0.ent67 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent67" "QuestionEntry" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -background {#333333} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#ffffff} \
        -text Question 
    vTcl:DefineAlias "$site_3_0.lab68" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent73 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent73" "CorrectEntry" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab74 \
        -background {#333333} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#ffffff} \
        -text {Correct Answer} 
    vTcl:DefineAlias "$site_3_0.lab74" "Label3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but75 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#333333} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Back 
    vTcl:DefineAlias "$site_3_0.but75" "BackButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but76 \
        -activebackground {#d9d9d9} -activeforeground {#ffffff} \
        -background {#333333} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Submit 
    vTcl:DefineAlias "$site_3_0.but76" "SubmitButton" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent79 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent79" "MaxMarks" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab80 \
        -background {#333333} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#ffffff} \
        -text {Max Marks} 
    vTcl:DefineAlias "$site_3_0.lab80" "Label4" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad81 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#333333} -disabledforeground {#a3a3a3} \
        -foreground {#0080ff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text a -value 1 -variable v 
    vTcl:DefineAlias "$site_3_0.rad81" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad82 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#333333} -disabledforeground {#a3a3a3} \
        -foreground {#0080ff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text b -value 2 -variable v 
    vTcl:DefineAlias "$site_3_0.rad82" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad83 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#333333} -disabledforeground {#a3a3a3} \
        -foreground {#0080ff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text c -value 3 -variable v 
    vTcl:DefineAlias "$site_3_0.rad83" "Radiobutton3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad84 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#333333} -disabledforeground {#a3a3a3} \
        -foreground {#0080ff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text d -value 4 -variable v 
    vTcl:DefineAlias "$site_3_0.rad84" "Radiobutton4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent85 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent85" "Option1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent86 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent86" "Option2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent87 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent87" "Option3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent88 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent88" "Option4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.ent67 \
        -in $site_3_0 -x 70 -y 60 -width 444 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 380 -y -300 -width 101 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent73 \
        -in $site_3_0 -x 540 -y 150 -width 34 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 400 -y 150 -width 129 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but75 \
        -in $site_3_0 -x 30 -y 290 -width 68 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but76 \
        -in $site_3_0 -x 280 -y 230 -anchor nw -bordermode ignore 
    place $site_3_0.ent79 \
        -in $site_3_0 -x 460 -y 20 -width 54 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab80 \
        -in $site_3_0 -x 360 -y 20 -width 88 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad81 \
        -in $site_3_0 -x 70 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.rad82 \
        -in $site_3_0 -x 70 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.rad83 \
        -in $site_3_0 -x 70 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.rad84 \
        -in $site_3_0 -x 70 -y 190 -anchor nw -bordermode ignore 
    place $site_3_0.ent85 \
        -in $site_3_0 -x 110 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.ent86 \
        -in $site_3_0 -x 110 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.ent87 \
        -in $site_3_0 -x 110 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.ent88 \
        -in $site_3_0 -x 110 -y 190 -anchor nw -bordermode ignore 
    label $top.lab62 \
        -background {#333333} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#ffffff} \
        -text {Add a Question} 
    vTcl:DefineAlias "$top.lab62" "Label" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra61 \
        -in $top -x 60 -y 140 -width 595 -relwidth 0 -height 345 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 240 -y 50 -width 194 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top60

